### PR TITLE
Fix #49

### LINKED ISSUE #49: Train classificator issue
```
Traceback (most recent call last):
  File "/ros_ws/src/serl/examples/pick_place_real/train_reward_classifier.py", line 160, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ros_ws/src/serl/examples/pick_place_real/train_reward_classifier.py", line 97, in main
    classifier = create_classifier(key, sample["next_observations"], image_keys)
  File "/ros_ws/src/serl/serl_launcher/serl_launcher/networks/reward_classifier.py", line 74, in create_classifier
    new_params = classifier.params.unfreeze()
AttributeError: 'dict' object has no attribute 'unfreeze'
I0515 10:52:56.182127 134645912520512 core.py:560] signal_shutdown [atexit]
```

### PR DESCRIPTION
**Pull request by realquantumcookie**

### CODE REVIEW

**Comment by jianlanluo** [comment]
Hi, can you provide some context for this?

**Comment by realquantumcookie** [comment]
Hi @jianlanluo, according to You Liang he bumped some dependency versions of serl which causes the reward classifier initialization to fail and causes some error messages when trying to save a checkpoint for the DroQ agent. You can see the issue referenced #49 for detail. We also experienced this issue when using it for the MoMA project with Oier and Laura and confirmed that the fix works. You Liang suggested me to open a PR for him to review.

**Review by youliangtan — APPROVED** [review]

**Comment by youliangtan** [comment]
thanks for addressing this dependency fix

**Comment by jianlanluo** [comment]
Hi, can you open another PR to fix the pre-commit error? this one broke it

**Comment by youliangtan** [comment]
fixed https://github.com/rail-berkeley/serl/commit/cdb787dcc48ebaedcb9d557ae66a770ccdfbaf1d

**Pull request merged**
